gg/# "qdapoHEADER"

:set noexpandtab
:set tabstop=12 shiftwidth=12
gg=G
:%s/BERRY_COMBOLUTED_DO_NOT_CHANGE_DO_REGEX/EXPAND_BERRY_COMBOLUTED_DO_NOT_CHANGE_DO_REGEX/g
:%s/BERRY_COMBOLUTED_DO_NOT_CHANGE_THEN_REGEX/EXPAND_BERRY_COMBOLUTED_DO_NOT_CHANGE_THEN_REGEX/g
gg=G
VG:w! /dev/stdout
:q!
