gg/# "qdapoHEADER"qp
:set noexpandtab
:set tabstop=8 shiftwidth=8
gg=G
:%s/BERRY_COMBOLUTED_DO_NOT_CHANGE_DO_REGEX/EXPAND_BERRY_COMBOLUTED_DO_NOT_CHANGE_DO_REGEX/g
:%s/BERRY_COMBOLUTED_DO_NOT_CHANGE_THEN_REGEX/EXPAND_BERRY_COMBOLUTED_DO_NOT_CHANGE_THEN_REGEX/g
gg=G
VG:w! FILE
:q!
